plugins {
    id 'java'
}

group = 'fr.hashtek'
version = 'R0.2.0-SNAPSHOT'

def hashrc = '/Users/ly/mc/hashrc'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    def props = [
        name: rootProject.name,
        version: version
    ]
    inputs.properties(props)
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(props)
    }
}

tasks.register('make', Copy) {
    from('build/libs')
    into(hashrc)
    include('*.jar')
}

tasks.make.dependsOn build
